default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: railsgram_development
  username: curso_user
  password: curs0_us3r
